### PR TITLE
Add infrastructure for hosting the admin platform

### PR DESCRIPTION
**Pull request by adrianclay**
We're placing this into a new EC2 container cluster as it will be a public application vs the API cluster which is private.

Any DOS attacks to the public admin platform shouldn't affect the rest of the service.

### CODE REVIEW

**Comment by adrianclay** [comment]
I'm a little disappointed about the amount of duplication we have between the different modules.  My thought for removing this duplication would be to introduce a module that our other modules could use, but I'm concerned about refactoring production infrastructure wanting to tear down what has been created and re-creating it.  I wonder if anybody has had any experience with this?

**Comment by emileswarts** [comment]
Your suggestion of extracting a module that other modules use is the only thing I can think of.
The userdata would be a prime candidate because it's so verbose.

Would add it to the backlog, if we do address it, it would be good to do it as an isolated task.

**Comment by adrianclay** [comment]
My fear with extracting it as a module will be that the resource ids will change, and so terraform will want to recreate the resources unless we do something like is explained here https://www.terraform.io/docs/commands/state/mv.html#example-move-a-resource-into-a-module

**Comment by adrianclay** [comment]
Also the RE jenkins terraform is an example of how you can do nice cloud inits https://github.com/alphagov/re-build-systems/tree/master/terraform/jenkins/cloud-init

**Pull request merged**
